import type { Metadata } from 'next';
import QueryProvider from './providers/QueryProvider';
import './globals.css';

export const metadata: Metadata = {
	title: 'back office',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<QueryProvider>{children}</QueryProvider>
			</body>
		</html>
	);
}
